version: '3'
services:
  express-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
     - mongo
   
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/Adeebuddin # Adjusted volume mapping for the MongoDB service
